### ISSUE TITLE
Device flow is disabled for the app id

### ISSUE THREAD

**Issue by wolfy1339** [octokit/create-octokit-project.js#208]
```
$ npm init octokit-project
(node:90316) ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
? Do you want to create a public or private repository? public
? If you have access, do you want to create the repository in the @octokit organization? No
./create-octokit-project.js/node_modules/@octokit/request/dist-node/index.js:88
      const error = new requestError.RequestError(toErrorMessage(data), status, {
                    ^

RequestError [HttpError]: Unknown error: {"error":"device_flow_disabled","error_description":"Device Flow must be explicitly enabled for this App","error_uri":"https://docs.github.com"}
    at ./create-octokit-project.js/node_modules/@octokit/request/dist-node/index.js:88:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async oauthRequest (./create-octokit-project.js/node_modules/@octokit/oauth-methods/dist-node/index.js:26:20)
    at async getOAuthAccessToken (./create-octokit-project.js/node_modules/@octokit/auth-oauth-device/dist-node/index.js:16:7)
    at async main (file://./create-octokit-project.js/index.js:69:21) {
  status: 400,
  response: {
    url: 'https://github.com/login/device/code',
    status: 400,
    headers: {
      'cache-control': 'no-cache',
      connection: 'close',
      'content-security-policy': "default-src 'none'; base-uri 'self'; block-all-mixed-content; child-src github.com/assets-cdn/worker/ gist.github.com/assets-cdn/worker/; connect-src 'self' uploads.github.com objects-origin.githubusercontent.com www.githubstatus.com collector.github.com raw.githubusercontent.com api.github.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com cdn.optimizely.com logx.optimizely.com/v1/events *.actions.githubusercontent.com wss://*.actions.githubusercontent.com online.visualstudio.com/api/v1/locations github-production-repository-image-32fea6.s3.amazonaws.com github-production-release-asset-2e65be.s3.amazonaws.com insights.github.com wss://alive.github.com; font-src github.githubassets.com; form-action 'self' github.com gist.github.com objects-origin.githubusercontent.com; frame-ancestors 'none'; frame-src viewscreen.githubusercontent.com notebooks.githubusercontent.com; img-src 'self' data: github.githubassets.com identicons.github.com github-cloud.s3.amazonaws.com secured-user-images.githubusercontent.com/ github-production-user-asset-6210df.s3.amazonaws.com customer-stories-feed.github.com spotlights-feed.github.com *.githubusercontent.com; manifest-src 'self'; media-src github.com user-images.githubusercontent.com/ secured-user-images.githubusercontent.com/; script-src github.githubassets.com; style-src 'unsafe-inline' github.githubassets.com; worker-src github.com/assets-cdn/worker/ gist.github.com/assets-cdn/worker/",
      'content-type': 'application/json; charset=utf-8',
      date: 'Tue, 25 Oct 2022 23:11:48 GMT',
      'expect-ct': 'max-age=2592000, report-uri="https://api.github.com/_private/browser/errors"',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-request-id': '845A:7A8C:647360:90121C:63586D34',
      'x-xss-protection': '0'
    },
    data: {
      error: 'device_flow_disabled',
      error_description: 'Device Flow must be explicitly enabled for this App',
      error_uri: 'https://docs.github.com'
    }
  },
  request: {
    method: 'POST',
    url: 'https://github.com/login/device/code',
    headers: {
      accept: 'application/json',
      'user-agent': 'octokit-auth-oauth-device.js/4.0.3 Node.js/16.15.0 (linux; x64)',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"client_id":"797fc7c2acb5f7c1bed3","scope":"public_repo"}'
  }
}
npm ERR! code 1
npm ERR! path ./openapi-webhooks
npm ERR! command failed
npm ERR! command sh -c create-octokit-project

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2022-10-25T23_11_41_315Z-debug-0.log
```

**Comment by gr2m** [comment]
Hmm odd, I thought I enabled the setting a while ago when the feature was rolled out

<img width="431" alt="image" src="https://user-images.githubusercontent.com/39992/197902437-2d048d69-fad3-403b-b691-f29dd0171269.png">

I enabled it again. Can you try again please?

**Comment by wolfy1339** [comment]
It works now :+1:
